server:
  port: 9090
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  undertow:
    max-http-post-size: 0
  http2:
    enabled: true
spring:
  application:
    name: cinema-service
  jmx: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://64.52.85.67/fourthwall_cinema_exercise?useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: webuser
    password: Abcd!234
    testOnBorrow: true
    validationQuery: Select 1
    hikari:
      poolName: Fourthwall Cinema - Prod
      auto-commit: false
      connectionTimeout: 30000
      idleTimeout: 60000
      maxLifetime: 20000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useConfigs: maxPerformance
        rewriteBatchedStatements: true
      maximum-pool-size: 5
    jpa:
      open-in-view: false
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.id.new_generator_mappings: true
        hibernate.connection.provider_disables_autocommit: true
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        # modify batch size as necessary
        hibernate.jdbc.batch_size: 25
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.query.fail_on_pagination_over_collection_fetch: true
        hibernate.query.in_clause_parameter_padding: true
        hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        hibernate.cache.use_minimal_puts: true
        hibernate.cache.hazelcast.instance_name: fsgateway
        hibernate.cache.hazelcast.use_lite_member: true
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

# ========================
# FW Logging
# ========================
logging:
  pattern:
    # Logging pattern for the console
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    # Logging pattern for file
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"
  # In properties file
  level:
    org.springframework: INFO
    com.abhisheksharma.fourthwall: INFO
  file:
    path: /var/log/application.log
springdoc:
  swagger-ui:
    path: /swagger-docs.html



# ===================================================================
# FW specific properties
# ===================================================================
fw:
  clientApp:
    name: "cinema-service"
  security:
    authentication:
      jwt:
        base64-secret: aYNVCXDscQvgyyBgiP2dhAZaAYzPk4DCapLj5iCd6HnvHV1OyRr4AbIrTwsjCydjsifzDyu4GLI6o00QY4GxDQ==
        # Token is valid 24 hours
        token-validity-in-seconds: 36000
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    address: do-no-reply@fourthwall-cinema.com
    personal: Fourthwall Cinema Email Center
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 600


application:
  omdbProp:
    url: http://www.omdbapi.com
    api-key: 5b4a7d9e